# Generated by Django 5.1.3 on 2024-11-23 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Cart", "0002_alter_cart_quantity"),
        ("Shop", "0003_alter_product_stock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("amount", models.IntegerField()),
                ("order_id", models.CharField(max_length=30)),
                ("razorpay_payment_id", models.CharField(blank=True, max_length=30)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("no_of_items", models.PositiveIntegerField()),
                ("phone", models.CharField(max_length=15)),
                ("pin", models.CharField(max_length=10)),
                ("order_id", models.CharField(max_length=30)),
                ("payment_status", models.CharField(default="Pending", max_length=30)),
                ("delivery_status", models.CharField(default="Pending", max_length=30)),
                ("ordered_date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Shop.product"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
