# Generated by Django 5.1.1 on 2024-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(),
        ),
    ]
